# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea45e45ad0bb97207bbb082bee6824bdbe9d4d47e872fc0f9599f99ea13a4233e7e0cf9a0e7893c522dbf5bb8927aec78f9e6a6887f45d5ee1ec5caf03a4325

test:
  secret_key_base: 86a60f4798531293253b460e7fbf40e7d0a85b4cbd8e908c6372c7eb70f0a2a0e3f33108a468587df5cd988e4fe5ab71eb456cb0816503189eca674a7037e8cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
